apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ip172-18-0-30-c5jfe05ac5og00e4fgm0.direct.labs.play-with-k8s.com
    http:
      paths:
      - backend:
          serviceName: webapp
          servicePort: 80
